initial  explicit SDP test coding

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1304,6 +1304,7 @@ Optional Features:
   --enable-unixdomain     include Unix Domain socket tests
   --enable-dlpi           include DLPI (link-layer) tests
   --enable-xti            include XTI socket tests
+  --enable-sdp            include SDP socket tests
   --enable-exs            include ICSC async sockets tests
   --enable-sctp           include tests to measure SCTP performance
   --enable-intervals      include ability to pace operations, may affect
@@ -7768,15 +7769,61 @@ fi
 
 case "$enable_xti" in
      yes)
+		use_xti=true
+		;;
+     no)
+		use_xti=false
+		;;
+     '')
+		use_xti=false
+		;;
+     *)
+		{ { echo "$as_me:$LINENO: error: --enable-xti takes yes or no" >&5
+echo "$as_me: error: --enable-xti takes yes or no" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+esac
+
+if $use_xti
+then
+	{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+else
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+if $use_xti
+then
+
+cat >>confdefs.h <<\_ACEOF
+#define WANT_XTI
+_ACEOF
+
+fi
+
+# see if we should be including the SDP tests
+
+{ echo "$as_me:$LINENO: checking whether to include SDP tests" >&5
+echo $ECHO_N "checking whether to include SDP tests... $ECHO_C" >&6; }
+
+# Check whether --enable-sdp was given.
+if test "${enable_sdp+set}" = set; then
+  enableval=$enable_sdp;
+fi
+
+
+case "$enable_sdp" in
+     yes)
 		# probably need to be a bit more sophisticated here
 
-{ echo "$as_me:$LINENO: checking for t_open in -lxti" >&5
-echo $ECHO_N "checking for t_open in -lxti... $ECHO_C" >&6; }
-if test "${ac_cv_lib_xti_t_open+set}" = set; then
+{ echo "$as_me:$LINENO: checking for t_open in -lsdp" >&5
+echo $ECHO_N "checking for t_open in -lsdp... $ECHO_C" >&6; }
+if test "${ac_cv_lib_sdp_t_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lxti  $LIBS"
+LIBS="-lsdp  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -7817,45 +7864,45 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_xti_t_open=yes
+  ac_cv_lib_sdp_t_open=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_xti_t_open=no
+	ac_cv_lib_sdp_t_open=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_xti_t_open" >&5
-echo "${ECHO_T}$ac_cv_lib_xti_t_open" >&6; }
-if test $ac_cv_lib_xti_t_open = yes; then
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_sdp_t_open" >&5
+echo "${ECHO_T}$ac_cv_lib_sdp_t_open" >&6; }
+if test $ac_cv_lib_sdp_t_open = yes; then
   cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBXTI 1
+#define HAVE_LIBSDP 1
 _ACEOF
 
-  LIBS="-lxti $LIBS"
+  LIBS="-lsdp $LIBS"
 
 fi
 
-		use_xti=true
+		use_sdp=true
 		;;
      no)
-		use_xti=false
+		use_sdp=false
 		;;
      '')
-		use_xti=false
+		use_sdp=false
 		;;
      *)
-		{ { echo "$as_me:$LINENO: error: --enable-xti takes yes or no" >&5
-echo "$as_me: error: --enable-xti takes yes or no" >&2;}
+		{ { echo "$as_me:$LINENO: error: --enable-sdp takes yes or no" >&5
+echo "$as_me: error: --enable-sdp takes yes or no" >&2;}
    { (exit 1); exit 1; }; }
 		;;
 esac
 
-if $use_xti
+if $use_sdp
 then
 	{ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
@@ -7864,11 +7911,11 @@ else
 echo "${ECHO_T}no" >&6; }
 fi
 
-if $use_xti
+if $use_sdp
 then
 
 cat >>confdefs.h <<\_ACEOF
-#define WANT_XTI
+#define WANT_SDP
 _ACEOF
 
 fi
