checkin first bits of non-working omni code

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -1305,6 +1305,7 @@ Optional Features:
                           results.
   --enable-unixdomain     include Unix Domain socket tests
   --enable-dlpi           include DLPI (link-layer) tests
+  --enable-omni           include OMNI (link-layer) tests
   --enable-xti            include XTI socket tests
   --enable-sdp            include SDP socket tests
   --enable-exs            include ICSC async sockets tests
@@ -7860,6 +7861,52 @@ then
 
 cat >>confdefs.h <<\_ACEOF
 #define WANT_DLPI
+_ACEOF
+
+fi
+
+# see if we should be including the OMNI tests
+
+{ echo "$as_me:$LINENO: checking whether to include OMNI tests" >&5
+echo $ECHO_N "checking whether to include OMNI tests... $ECHO_C" >&6; }
+
+# Check whether --enable-omni was given.
+if test "${enable_omni+set}" = set; then
+  enableval=$enable_omni;
+fi
+
+
+case "$enable_omni" in
+     yes)
+		use_omni=true
+		;;
+     no)
+		use_omni=false
+		;;
+     '')
+		use_omni=false
+		;;
+     *)
+		{ { echo "$as_me:$LINENO: error: --enable-omni takes yes or no" >&5
+echo "$as_me: error: --enable-omni takes yes or no" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+esac
+
+if $use_omni
+then
+	{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+else
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+if $use_omni
+then
+
+cat >>confdefs.h <<\_ACEOF
+#define WANT_OMNI
 _ACEOF
 
 fi
