teach omni tests how to find interface slot id

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -706,6 +706,7 @@ NEED_LIBCOMPAT_TRUE
 NEED_LIBCOMPAT_FALSE
 NETCPU_SOURCE
 NETRTLKUP_SOURCE
+NETSLOTLKUP_SOURCE
 NETDRVLKUP_SOURCE
 LTLIBOBJS'
 ac_subst_files=''
@@ -1322,6 +1323,8 @@ Optional Features:
   --enable-cpuutil        include code to measure CPU utilization using
                           specified mechanism
   --enable-rtlookup       include code to find the probable egress interface
+                          using specified mechanism
+  --enable-slotlookup     include code to find the probable egress interface
                           using specified mechanism
   --enable-drvlookup      include code to find the probable egress interface
                           using specified mechanism
@@ -9582,7 +9585,64 @@ echo "${ECHO_T}\"$enable_rtlookup\"" >&6; }
 
 
 
-# time to see about route lookup mechanisms
+# time to see about slot lookup mechanisms
+
+{ echo "$as_me:$LINENO: checking which slot lookup type to use" >&5
+echo $ECHO_N "checking which slot lookup type to use... $ECHO_C" >&6; }
+
+# Check whether --enable-slotlookup was given.
+if test "${enable_slotlookup+set}" = set; then
+  enableval=$enable_slotlookup;
+fi
+
+
+NETSLOTLKUP_SOURCE="$enable_slotlookup"
+case "$enable_slotlookup" in
+
+	linsys)
+		use_slotlookup=true
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_LINSYS
+_ACEOF
+
+		;;
+	'')
+# guess it automagically in a nice big case statement
+		case $target in
+		     *-*-linux*)
+			use_slotlookup=true
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_LINSYS
+_ACEOF
+
+			enable_slotlookup="linux - auto"
+			NETSLOTLKUP_SOURCE="linux"
+			;;
+		     *)
+			use_slotlookup=false
+			NETSLOTLKUP_SOURCE="none"
+			enable_slotlookup="none. Consider teaching configure about your platform."
+			;;
+		esac
+		;;
+	none)
+		use_slotlookup=false
+		;;
+	*)
+		{ { echo "$as_me:$LINENO: error: --enable-slotlookup takes linux or none" >&5
+echo "$as_me: error: --enable-slotlookup takes linux or none" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+esac
+
+	{ echo "$as_me:$LINENO: result: \"$enable_slotlookup\"" >&5
+echo "${ECHO_T}\"$enable_slotlookup\"" >&6; }
+
+
+
+# time to see about driver lookup mechanisms
 
 { echo "$as_me:$LINENO: checking which driver info lookup type to use" >&5
 echo $ECHO_N "checking which driver info lookup type to use... $ECHO_C" >&6; }
@@ -10390,11 +10450,12 @@ NEED_LIBCOMPAT_TRUE!$NEED_LIBCOMPAT_TRUE$ac_delim
 NEED_LIBCOMPAT_FALSE!$NEED_LIBCOMPAT_FALSE$ac_delim
 NETCPU_SOURCE!$NETCPU_SOURCE$ac_delim
 NETRTLKUP_SOURCE!$NETRTLKUP_SOURCE$ac_delim
+NETSLOTLKUP_SOURCE!$NETSLOTLKUP_SOURCE$ac_delim
 NETDRVLKUP_SOURCE!$NETDRVLKUP_SOURCE$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 94; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 95; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
